name: library_flutter
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  auto_route: ^9.2.2
  dio: ^5.6.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.3.2
  toastification: ^2.1.0
  dot_curved_bottom_nav: ^0.0.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/adaptive_icon.png"
